:project:
  :build_root: build
  :test_file_prefix: test_
  :use_test_preprocessor: :all
  :use_auxiliary_dependencies: true

  :default_tasks:
    - test:all

  :use_backtrace: :none

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:Test/**
    - -:Test/support/**

  :source:
    - +:Core/**

  :include:
    - +:Core/**

  :support:
    - +:Test/support/**

  :libraries: []

:defines:
  :common: &common_defines
    []

  :test:
    - *common_defines
    - TEST

  :test_preprocess:
    - *common_defines
    - TEST

:unity:
  :use_param_tests: false

:test_runner:
  :cmdline_args: false

  :includes: []
  :defines: []
  :file_suffix: _runner

:cmock:
  :mock_prefix: mock_
  :mock_suffix: ""

  :when_no_prototypes: :warn
  :enforce_strict_ordering: true

  :plugins:
    - :ignore
    - :callback

  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8

:plugins:
  :load_paths: []
  :enabled: []