set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_GNU_TOOLCHAIN_BIN "" CACHE PATH "ARM GNU toolchain bin path")

if(CMAKE_HOST_WIN32) 
    set(TOOLCHAIN_EXECUTABLE_SUFFIX ".exe") 
else() 
    set(TOOLCHAIN_EXECUTABLE_SUFFIX "") 
endif()

set(CMAKE_C_COMPILER   "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-gcc${TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-g++${TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_ASM_COMPILER "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-gcc${TOOLCHAIN_EXECUTABLE_SUFFIX}")

set(CMAKE_AR     "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-ar${TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_RANLIB "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-ranlib${TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_NM     "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-nm${TOOLCHAIN_EXECUTABLE_SUFFIX}")

set(CMAKE_OBJCOPY "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-objcopy${TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_SIZE    "${ARM_GNU_TOOLCHAIN_BIN}/arm-none-eabi-size${TOOLCHAIN_EXECUTABLE_SUFFIX}")

# Evitar que CMake encuentre librerías/headers del host por accidente
set(CMAKE_FIND_ROOT_PATH "${ARM_GNU_TOOLCHAIN_BIN}/..")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
