name: Test renesas install enviroment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v7

    - name: Install dependencies (CMake, Ruby, Ceedling, Clang-Tidy)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential ruby ruby-dev gdb clang-tidy curl ninja-build

    - name: Install Ceedling
      run: sudo gem install ceedling --no-document

    - name: Download FSP studio 6.1.0
      run: |
       curl -L -O "https://github.com/renesas/fsp/releases/download/v6.1.0/setup_fsp_v6_1_0_e2s_v2025-07.xz.run"
       sudo chmod +x setup_fsp_v6_1_0_e2s_v2025-07.xz.run
    
    - name: Install FSP studio 6.1.0
      run: |
       sudo ./setup_fsp_v6_1_0_e2s_v2025-07.xz.run --accept --nox11  -- --launcher.suppressErrors -nosplash -install.silent -install.Declipse.p2.default.renesas.installPath=/root/renesas

    - name: Verify Renesas toolchain
      shell: bash
      run: |
        set -euxo pipefail

        sudo /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc --version
        sudo /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ --version
        sudo /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-size --version

    - name: Verify development environment
      shell: bash
      run: |
        set -euxo pipefail

        cmake --version
        ninja --version
        clang-tidy --version
        ruby --version
        ceedling version

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake for HOST
      run: |
        cmake -S . -B build -G Ninja \
              -DARM_GNU_TOOLCHAIN_BIN="/root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/13.2.rel1/bin" \
              -DCMAKE_BUILD_TYPE=Debug -DPLATFORM=RA6T2