name: Test renesas install enviroment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies (CMake, MinGW, Ruby, Ceedling, Clang-Tidy)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential ruby ruby-dev gdb clang-tidy curl

    - name: Download FSP studio 6.1.0
      run: |
       curl -L -O "https://github.com/renesas/fsp/releases/download/v6.1.0/setup_fsp_v6_1_0_e2s_v2025-07.xz.run"
       sudo chmod +x setup_fsp_v6_1_0_e2s_v2025-07.xz.run
    
    - name: Install FSP studio 6.1.0
      run: |
       sudo ./setup_fsp_v6_1_0_e2s_v2025-07.xz.run --accept --nox11  -- --launcher.suppressErrors -nosplash -install.silent -install.Declipse.p2.default.renesas.installPath=/opt/renesas

    - name: Verify Renesas toolchain
      shell: bash
      run: |
        set -euxo pipefail

        /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc --version
        /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-g++ --version
        /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gdb --version
        /root/renesas/ra/e2studio_v2025-07_fsp_v6.1.0/toolchains/gcc_arm/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-size --version

    - name: Verify development environment
      shell: bash
      run: |
        set -euxo pipefail

        cmake --version
        ninja --version
        clang-tidy --version
        ruby --version
        ceedling version